backend:
  name: github
  repo: bsubedi26/gatsby-netlify

media_folder: static/assets
public_folder: assets

publish_mode: editorial_workflow

collections:
  - name: discover
    label: Discover project
    folder: discover
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { name: image, label: Header Image, widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
